name: kivicare_flutter
description: A new Flutter application.

publish_to: 'none'

#Todo update version before making code zip     DO NOT REMOVE THIS TODO
version: 9.6.6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6

  cupertino_icons: ^1.0.8

  #Firebase Notification
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

  firebase_remote_config: ^5.4.4
  google_fonts: ^6.2.1
  moment_dart: ^5.2.3

  #State Management Technique
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  nb_utils: ^7.1.4
#  scan: ^1.6.0
  # mobile_scanner: ^7.0.0


  #API calling
  http: ^1.4.0
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-alpha.6

  # Images and Icons
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.12.0
  flutter_slidable: ^4.0.0
  percent_indicator: ^4.2.5
  signature: ^6.0.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  # bar chart
  fl_chart: ^1.0.0

  #APP Information
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  flutter_custom_tabs: ^2.4.0
  get_storage: ^2.1.1

  # Pickers for image and file and dates
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  open_file: ^3.5.10
  syncfusion_flutter_datepicker: ^29.2.5
  lottie: ^3.3.1


  #PAYMENT
  razorpay_flutter: ^1.4.0
  flutter_stripe: ^11.5.0

  # MAP
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.15

  #dart run build_runner build --delete-conflicting-outputs


flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - images/flags/
    - images/filesFormat/
    - images/icons/ic_addToCart.png